### PR TITLE
Retry with context & change server's shutdown

### PR DESCRIPTION
**Pull request by nvthongswansea**
This PR will change:
- Retrial will fully depend on the contexts that are passed to the retry-able functions. If an empty context is provided, the function will keep retrying until some conditions are met.
- Shutting down a server won't turn off the server (in case the server cannot be shutdown gracefully). If the server cannot be shutdown, the user have to turn it off via `StopServer` function.

### CODE REVIEW

**Comment by nvthongswansea** [comment]
> @nvthongswansea plz update README with related changes

Done

**Comment by itakouna** [comment]
As we switch from timeout to context, I would suggest removing `requestCheckTimeoutSecs` because it's only used for waiting servers to change power status. I would keep it as an internal constant. `RequestCheckTimeout`  will might confuse users. what do you think? @nvthongswansea

**Comment by nvthongswansea** [comment]
> As we switch from timeout to context, I would suggest removing `requestCheckTimeoutSecs` because it's only used for waiting servers to change power status. I would keep it as an internal constant. `RequestCheckTimeout` will might confuse users. what do you think? @nvthongswansea

Strange. I've already removed it since the beginning. Can you check where it is, please?

**Comment by itakouna** [comment]
> > As we switch from timeout to context, I would suggest removing `requestCheckTimeoutSecs` because it's only used for waiting servers to change power status. I would keep it as an internal constant. `RequestCheckTimeout` will might confuse users. what do you think? @nvthongswansea
> 
> Strange. I've already removed it since the beginning. Can you check where it is, please?

It lease, I can see it in README ` 120, //Timeout (in seconds) of checking requests`

**Comment by nvthongswansea** [comment]
> > > As we switch from timeout to context, I would suggest removing `requestCheckTimeoutSecs` because it's only used for waiting servers to change power status. I would keep it as an internal constant. `RequestCheckTimeout` will might confuse users. what do you think? @nvthongswansea
> > 
> > 
> > Strange. I've already removed it since the beginning. Can you check where it is, please?
> 
> It lease, I can see it in README ` 120, //Timeout (in seconds) of checking requests`

Done

**Pull request merged**
