### PR TITLE
Add missing fields & Remove unnecessary server hw profiles.

### PR DESCRIPTION
**Pull request by nvthongswansea**
- Remove unnecessary server hw profiles: "q35_nested". 
- Add missing field `StorageVariant ` to `StorageProperties`.

### CODE REVIEW

**Comment by bkircher** [comment]
Code is fine but not sure we really want these to be exposed or used anyone.  @MarcHarriss Any thoughts?

**Comment by MarcHarriss** [comment]
yep, ack @bkircher 👍

**Comment by nvthongswansea** [comment]
@bkircher @MarcHarriss please do another review. Thanks!

**Comment by MarcHarriss** [comment]
looks good @nvthongswansea

**Review by bkircher — APPROVED** [review]
Thanks!

**Pull request merged**
