### PR TITLE
Marketplace implementation

### PR DESCRIPTION
**Pull request by nvthongswansea**

### CODE REVIEW

**Comment by itakouna** [comment]
@nvthongswansea plz, fix the conflict. An example of this resource is missing.

**Comment by nvthongswansea** [comment]
> @nvthongswansea plz, fix the conflict. An example of this resource is missing.

An example cannot be provided as this functionality is only available to administrator account currently (according to dev team). I don't even know why they made these API endpoints public.

**Comment by fkr** [comment]
@nvthongswansea leave the create part out for now.

**Comment by itakouna** [comment]
I'm going to close due to none active development.

**Pull request closed without merging**
