### PR TITLE
Change json field `storage_backups`'s name to `storages_backups`

### PR DESCRIPTION
**Pull request by nvthongswansea**
Fix issue https://github.com/gridscale/gsclient-go/issues/145

### CODE REVIEW

**Review by bkircher — APPROVED** [review]
Gonna trust you on this. Checked API docs but no hint on output schema with https://api.gridscale.io/objects/storages/{storage_uuid}/backups

**Comment by nvthongswansea** [comment]
> Gonna trust you on this. Checked API docs but no hint on output schema with [https://api.gridscale.io/objects/storages/{storage_uuid}/backups](https://api.gridscale.io/objects/storages/%7Bstorage_uuid%7D/backups)

image

**Comment by nvthongswansea** [comment]
The docs for https://api.gridscale.io/objects/storages/{storage_uuid}/backups is ok but https://api.gridscale.io/objects/storages/{storage_uuid}/backup_schedules is not.

**Comment by bkircher** [comment]
:+1:

**Pull request merged**
